[package]
name = "rust_test_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
log = "0.4.22"
mime = "0.3.17"
pretty_env_logger = "0.5.0"
teloxide = { version = "0.12.2", features = ["macros"] }
tokio = { version = "1.38.1", features = ["rt-multi-thread", "macros"] }
